
openapi: 3.0.3
info:
  title: Agentic Portfolio Platform
  version: 1.0.0
  description: >
    Contracts-first APIs for the Agentic AI Portfolio Manager (brokerless).
    Generated 2025-08-29. Security is JWT bearer. Errors follow RFC7807 (problem+json).
servers:
  - url: http://localhost:8080
    description: API Gateway (local)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Problem:
      type: object
      properties:
        type: {"type":"string","format":"uri"}
        title: {"type":"string"}
        status: {"type":"integer"}
        detail: {"type":"string"}
        instance: {"type":"string","format":"uri"}
    Candle:
      type: object
      required: [ts, open, high, low, close, volume, symbol, tf, venue]
      properties:
        ts: { type: string, format: date-time }
        open: { type: number }
        high: { type: number }
        low: { type: number }
        close: { type: number }
        volume: { type: number }
        symbol: { type: string }
        tf: { type: string, example: "1d" }
        venue: { type: string, example: "NASDAQ" }
    KPI:
      type: object
      properties:
        pnl: { type: number }
        sharpe: { type: number }
        drawdown: { type: number }
        gross: { type: number }
        net: { type: number }
    Position:
      type: object
      properties:
        symbol: { type: string }
        qty: { type: number }
        avg_price: { type: number }
        side: { type: string, enum: ["LONG","SHORT"] }
        opened_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    Watchlist:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        user_id: { type: string, format: uuid }
        created_at: { type: string, format: date-time }
security:
  - bearerAuth: []




paths:
  /api/risk/rules:
    get:
      summary: List risk/compliance rules
      responses:
        "200":
          description: Rules
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string, format: uuid }
                    name: { type: string }
                    config: { type: object }
                    enabled: { type: boolean }
    post:
      summary: Create or update a rule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, config]
              properties:
                id: { type: string, format: uuid }
                name: { type: string }
                config: { type: object }
                enabled: { type: boolean }
      responses:
        "200": { description: Upserted }
  /api/risk/check:
    post:
      summary: Evaluate risk for order intents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [portfolio_id, intents]
              properties:
                portfolio_id: { type: string, format: uuid }
                intents:
                  type: array
                  items:
                    type: object
                    properties:
                      symbol: { type: string }
                      side: { type: string, enum: [BUY, SELL] }
                      qty: { type: number }
                      notional: { type: number }
                exposures: { type: object }
      responses:
        "200":
          description: Risk decision
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: [APPROVED, REJECTED] }
                  reasons: { type: array, items: { type: string } }
  /api/compliance/blacklist:
    get:
      summary: Get symbol blacklist
      responses:
        "200":
          description: Blacklist
          content:
            application/json:
              schema:
                type: array
                items: { type: string }
    post:
      summary: Replace symbol blacklist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbols:
                  type: array
                  items: { type: string }
      responses:
        "200": { description: Updated }
  /api/compliance/attestations:
    post:
      summary: Record an attestation event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                portfolio_id: { type: string, format: uuid }
                message: { type: string }
      responses:
        "201": { description: Created }
